# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "52628660d0cc19535697c8af0fac239e"
name = "Logistics"
handle = "logistics-11"
application_url = "https://tar-chronic-steven-feat.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-978c50de.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://tar-chronic-steven-feat.trycloudflare.com/auth/callback",
  "https://tar-chronic-steven-feat.trycloudflare.com/auth/shopify/callback",
  "https://tar-chronic-steven-feat.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
